apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml
  - daemonset.yaml

components:
  - ../../components/filebeat-image

configMapGenerator:
  - name: filebeat-config
    namespace: stage3-collector
    files:
      - filebeat.yml

generatorOptions:
  labels:
    app.kubernetes.io/name: filebeat
    app.kubernetes.io/component: log-collector
    app.kubernetes.io/part-of: distributed-log-platform
    distributed-log-platform.io/purpose: log-collection
  # 配置变化会更新引用名称并触发 DaemonSet 滚动更新。
  disableNameSuffixHash: false
