apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: stage3-collector
  labels:
    app.kubernetes.io/name: filebeat
    app.kubernetes.io/component: log-collector
    app.kubernetes.io/part-of: distributed-log-platform
    distributed-log-platform.io/purpose: log-collection
