apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/component: search-storage
    app.kubernetes.io/part-of: distributed-log-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: http
      protocol: TCP
