apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 资源跨越两个命名空间，禁止使用全局 namespace transformer。
resources:
  - ../../base/filebeat
  - ../../base/filebeat-metadata-access

images:
  - name: docker.elastic.co/beats/filebeat-wolfi
    newName: docker.elastic.co/beats/filebeat-wolfi
    newTag: 9.4.4

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: filebeat
      namespace: stage3-collector
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: filebeat
        namespace: stage3-collector
      spec:
        template:
          spec:
            containers:
              - name: filebeat
                imagePullPolicy: Never
