apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage3-logs

resources:
  - ../../base/kafka-topics

# 本地 Job 使用已经旁加载的 Kafka 4.3.1 镜像。
images:
  - name: apache/kafka
    newName: apache/kafka
    newTag: 4.3.1

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: kafka-topic-initializer
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: kafka-topic-initializer
      spec:
        template:
          spec:
            containers:
              - name: kafka-topic-initializer
                imagePullPolicy: Never
